CREATE TABLE IF NOT EXISTS tb_instituicao (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        codigo TEXT NOT NULL,
        nome TEXT NOT NULL,
        co_regiao INTEGER NOT NULL,
        no_regiao INTEGER NOT NULL,
        co_uf INTEGER NOT NULL,
        no_uf INTEGER NOT NULL,
        co_municipio INTEGER NOT NULL,
        qt_mat_bas INTEGER NOT NULL,
        qt_mat_prof INTEGER NOT NULL,
        qt_mat_eja INTEGER NOT NULL,
        qt_mat_esp INTEGER NOT NULL,
        qt_mat_fund INTEGER NOT NULL,
        qt_mat_inf INTEGER NOT NULL,
        qt_mat_med INTEGER NOT NULL,
        qt_mat_zr_na INTEGER NOT NULL,
        qt_mat_zr_rur INTEGER NOT NULL,
        qt_mat_zr_urb INTEGER NOT NULL
);